### ISSUE TITLE
[Crash] 1.3.0 MobStrengthener.changeAttributes NPE crashed server

### ISSUE THREAD

**Issue by kirchner-trevor** [Globox1997/RpgDifficulty#43]
Minecraft Version: 1.19.2
RpgDifficultyVersion: 1.3.0
Fabric Version: 0.14.8
Base Modpack: Better MC v9 (my modpack is https://www.curseforge.com/minecraft/modpacks/turtley-awesome)

Full server crash when players traveled far enough out to trigger a mob to spawn with increased strength. This is the first time a player has traveled far enough since the server had been on.

`java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5132.method_26864(net.minecraft.class_1320)" because the return value of "java.util.Map.get(Object)" is null
	at net.rpgdifficulty.api.MobStrengthener.changeAttributes(MobStrengthener.java:189)
	at net.minecraft.class_3218.handler$eid000$spawnEntityMixin(class_3218.java:17215)
	at net.minecraft.class_3218.method_8649(class_3218.java)
	at org.betterx.betternether.entity.EntityNaga.method_7105(EntityNaga.java:60)
	at net.minecraft.class_1381.method_6268(class_1381.java:96)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:753)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)`

Logs: [crash-2022-11-04_22.43.58-server.txt](https://github.com/Globox1997/RpgDifficulty/files/9944095/crash-2022-11-04_22.43.58-server.txt)
Config: [rpgdifficulty.txt](https://github.com/Globox1997/RpgDifficulty/files/9944097/rpgdifficulty.txt)

**Comment by Globox1997** [comment]
Does this also happen with the latest rpgdifficulty mod?

**Comment by kirchner-trevor** [comment]
I have not tried the latest version. Will the 1.3.0 client work with the 1.3.1 server? If so I can try it tonight, otherwise I will need to wait until next week to push out the new modpack with 1.3.1.

**Comment by Globox1997** [comment]
I think it should work server only but no need to update a whole modpack for just a test

**Comment by Globox1997** [comment]
I think with the latest version this won't happen, reopen if still existent
