### ISSUE TITLE
Gradle can't find the "Nameplate" Library, and hence the build fails

### ISSUE THREAD

**Issue by Morxemplum** [Globox1997/RpgDifficulty#57]
I'm deciding to move this from the Discord over onto Github so that this issue can be indexed through a search. 

Basically, I am playing on Minecraft 1.19.3, and I found this mod to be interesting, and tried to apply the prebuilt jar from CurseForge. However, the game doesn't launch and comes with this error:

```
[14:22:58] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: field_23781
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.NoSuchFieldError: field_23781
	at net.minecraft.class_5134.handler$zkh000$rpgdifficulty$registerMixin(class_5134.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.class_5134.method_26871(class_5134.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_5134.<clinit>(class_5134.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_1294.<clinit>(class_1294.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:262) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 5 more
Process exited with code 1.
```
I thought this was an error because of an incompatibility with 1.19.2 and possibly some of the fabric libraries, so I intend to try and update this project to 1.19.3 (and 1.19.4, more than likely). I cloned the repository, and I just decided to run gradle on the repository, just to see if the project builds. Unfortunately, I run into this error with Gradle.

```
> Configure project :
Fabric Loom: 1.1.14
Found existing cache lock file, rebuilding loom cache. This may have been caused by a failed or canceled build.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'RpgDifficulty'.
> Could not resolve all files for configuration ':modCompileOnly'.
   > Could not find com.github.Globox1997:Nameplate:1.19-SNAPSHOT.
     Searched in the following locations:
       - file:/home/morxemplum/Gits/RpgDifficulty/.gradle/loom-cache/remapped_mods/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - file:/home/morxemplum/Gits/RpgDifficulty/.gradle/loom-cache/remapped_mods/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - file:/home/morxemplum/.gradle/caches/fabric-loom/minecraftMaven/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - file:/home/morxemplum/.gradle/caches/fabric-loom/minecraftMaven/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - file:/home/morxemplum/Gits/RpgDifficulty/.gradle/loom-cache/minecraftMaven/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - file:/home/morxemplum/Gits/RpgDifficulty/.gradle/loom-cache/minecraftMaven/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://maven.fabricmc.net/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://maven.fabricmc.net/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://libraries.minecraft.net/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://libraries.minecraft.net/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://libraries.minecraft.net/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.jar
       - https://repo.maven.apache.org/maven2/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://maven.shedaniel.me/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://maven.shedaniel.me/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://maven.terraformersmc.com/releases/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://maven.terraformersmc.com/releases/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://jitpack.io/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://maven.bai.lol/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://maven.bai.lol/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://www.cursemaven.com/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://www.cursemaven.com/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
       - https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/maven-metadata.xml
       - https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/com/github/Globox1997/Nameplate/1.19-SNAPSHOT/Nameplate-1.19-SNAPSHOT.pom
     Required by:
         project :
```

It seems like the error is coming from Gradle not being able to find the proper build of the "Nameplate" Library, and hence can't progress further with the build. When talking with @Globox1997 about this, they claim that Jitpack, one of the repositories hosting the library, didn't have the latest build working.

If you are curious about the Gradle daemon, here is the --version info. The JVM shouldn't matter, as the gradle build specifies to use Java 17.

```
------------------------------------------------------------
Gradle 8.1
------------------------------------------------------------

Build time:   2023-04-13 09:32:00 UTC
Revision:     <unknown>

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_362 (Oracle Corporation 25.362-b09)
OS:           Linux 6.2.11-arch1-1 amd64
```

Looking forward to keeping this mod alive! :)

**Comment by Globox1997** [comment]
This mod is definitely alive ;)
Use the modrinth maven just as I did since mc 1.20.
