### ISSUE TITLE
Game crashing on 1.20.6

### ISSUE THREAD

**Issue by snipcola** [Globox1997/RpgDifficulty#77]
### Information
**Minecraft Version:** 1.20.6
**Mod Loader Version:** 0.15.11
**Mod Version:** 1.1.1

### Issue
The game crashes upon launch.

### Mods
- Fabric API
- Cloth Config API
- RpgDifficulty

### Logs
<details>
  <summary>latest.log</summary>
  
```
[22:19:45] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.11
[22:19:45] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[22:19:45] [main/INFO]: Loading 56 mods:
	- cloth-config 14.0.126
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.98.0+1.20.6
	   |-- fabric-api-base 0.4.40+80f8cf51b0
	   |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72bb0
	   |-- fabric-biome-api-v1 13.0.25+be5d88beb0
	   |-- fabric-block-api-v1 1.0.20+6dfe4c9bb0
	   |-- fabric-block-view-api-v2 1.0.8+80f8cf51b0
	   |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf51b0
	   |-- fabric-client-tags-api-v1 1.1.12+7f945d5bb0
	   |-- fabric-command-api-v1 1.2.45+f71b366fb0
	   |-- fabric-command-api-v2 2.2.24+80f8cf51b0
	   |-- fabric-commands-v0 0.2.62+df3654b3b0
	   |-- fabric-content-registries-v0 8.0.5+b82b2392b0
	   |-- fabric-convention-tags-v1 2.0.4+7f945d5bb0
	   |-- fabric-convention-tags-v2 2.1.0+70fd1b46b0
	   |-- fabric-crash-report-info-v1 0.2.27+80f8cf51b0
	   |-- fabric-data-attachment-api-v1 1.1.16+2a2c66b6b0
	   |-- fabric-data-generation-api-v1 19.1.0+ad474493b0
	   |-- fabric-dimensions-v1 2.1.68+94793913b0
	   |-- fabric-entity-events-v1 1.6.8+e9d2a72bb0
	   |-- fabric-events-interaction-v0 0.7.6+c5fc38b3b0
	   |-- fabric-game-rule-api-v1 1.0.50+80f8cf51b0
	   |-- fabric-item-api-v1 8.2.0+5bcea88ab0
	   |-- fabric-item-group-api-v1 4.0.39+aae0949ab0
	   |-- fabric-key-binding-api-v1 1.0.45+80f8cf51b0
	   |-- fabric-keybindings-v0 0.2.43+df3654b3b0
	   |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b3b0
	   |-- fabric-loot-api-v2 3.0.5+97f703dab0
	   |-- fabric-message-api-v1 6.0.10+109a837cb0
	   |-- fabric-model-loading-api-v1 1.0.12+80f8cf51b0
	   |-- fabric-models-v0 0.4.11+9386d8a7b0
	   |-- fabric-networking-api-v1 4.0.8+0dca0349b0
	   |-- fabric-object-builder-api-v1 15.1.4+c5fc38b3b0
	   |-- fabric-particles-v1 4.0.0+c5fc38b3b0
	   |-- fabric-recipe-api-v1 5.0.3+c5fc38b3b0
	   |-- fabric-registry-sync-v0 5.0.16+ad474493b0
	   |-- fabric-renderer-api-v1 3.2.12+97f703dab0
	   |-- fabric-renderer-indigo 1.5.12+80f8cf51b0
	   |-- fabric-renderer-registries-v1 3.2.61+df3654b3b0
	   |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eb0
	   |-- fabric-rendering-fluids-v1 3.1.3+2c869dedb0
	   |-- fabric-rendering-v0 1.1.64+df3654b3b0
	   |-- fabric-rendering-v1 4.2.4+b21c00cbb0
	   |-- fabric-resource-conditions-api-v1 4.1.0+83154f1bb0
	   |-- fabric-resource-loader-v0 1.1.0+c0e5481fb0
	   |-- fabric-screen-api-v1 2.0.21+7b70ea8ab0
	   |-- fabric-screen-handler-api-v1 1.3.73+8c7b71c2b0
	   |-- fabric-sound-api-v1 1.0.21+c5fc38b3b0
	   |-- fabric-transfer-api-v1 5.1.6+c5fc38b3b0
	   \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f560b0
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.20.6
	- rpgdifficulty 1.1.1
[22:19:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/********/Library/Application%20Support/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:19:46] [main/INFO]: Compatibility level set to JAVA_17
[22:19:47] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[22:19:50] [main/ERROR]: Mixin apply for mod rpgdifficulty failed rpgdifficulty.mixins.json:entity.ZombieEntityMixin from mod rpgdifficulty -> net.minecraft.class_1642: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onTrackedDataSetMixin could not find any targets matching 'Lnet/minecraft/class_1642;onTrackedDataSet(Lnet/minecraft/class_2940;)V' in net.minecraft.class_1642. Using refmap rpgdifficulty-refmap.json [PREINJECT Applicator Phase -> rpgdifficulty.mixins.json:entity.ZombieEntityMixin from mod rpgdifficulty -> Prepare Injections ->  -> handler$zng000$rpgdifficulty$onTrackedDataSetMixin(Lnet/minecraft/class_2940;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onTrackedDataSetMixin could not find any targets matching 'Lnet/minecraft/class_1642;onTrackedDataSet(Lnet/minecraft/class_2940;)V' in net.minecraft.class_1642. Using refmap rpgdifficulty-refmap.json [PREINJECT Applicator Phase -> rpgdifficulty.mixins.json:entity.ZombieEntityMixin from mod rpgdifficulty -> Prepare Injections ->  -> handler$zng000$rpgdifficulty$onTrackedDataSetMixin(Lnet/minecraft/class_2940;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) [?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:213) [client-intermediary.jar:?]
	at net.minecraft.item.Items.<clinit>(Items.java:855) [client-intermediary.jar:?]
	at net.minecraft.block.LightBlock.getOutlineShape(LightBlock.java:64) [client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(class_4970.java:1057) [client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(class_4970.java:1053) [client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock.getCollisionShape(AbstractBlock.java:356) [client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(class_4970.java:1336) [client-intermediary.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(class_4970.java:868) [client-intermediary.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:1260) [client-intermediary.jar:?]
	at net.minecraft.block.FireBlock.registerDefaultFlammables(FireBlock.java:336) [client-intermediary.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:53) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:170) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
[22:19:50] [Datafixer Bootstrap/INFO]: 222 Datafixer optimizations took 234 milliseconds
[22:19:51] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:183) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:172) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:872) ~[client-intermediary.jar:?]
	at net.minecraft.util.SystemDetails.addSection(SystemDetails.java:66) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient.java:2593) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient.java:2564) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
```
  
</details>

**Comment by Shadowpudding** [comment]
Same issue. Disabeling the mod lets the game launch. 

Log
[crash-2024-05-30_15.44.52-client.txt](https://github.com/Globox1997/RpgDifficulty/files/15500829/crash-2024-05-30_15.44.52-client.txt)

**Comment by KohlrabitoDev** [comment]
Same. Not even going to attach log. It's probably word for word :(

**Comment by makumaku1974** [comment]
mine not even crashing

**Comment by makumaku1974** [comment]
btw how to increase the level capped at Level 20...

**Comment by Globox1997** [comment]
Fixed it
