### ISSUE TITLE
When my friends try to join the server it crashes

### ISSUE THREAD

**Issue by AzCreep** [Globox1997/RpgDifficulty#82]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.9

### Mod Version

1.3.17

### Describe the Issue

So it's pretty much this:
[16:03:57] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.rpgdifficulty.api.MobStrengthener.changeAttributes(net.minecraft.class_1308, net.minecraft.class_1937)'
        at knot/net.nameplate.network.NameplateServerPacket.lambda$init$0(NameplateServerPacket.java:26) ~[nameplate-1.1.5.jar:?]
        at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

### latest.log

[latest.log](https://github.com/user-attachments/files/18011175/latest.log)

### Do you use any other mods except the required ones?

yes i'm using a full modpack but for some reason it started now

**Comment by AzCreep** [comment]
[2024-12-04-7.log.gz](https://github.com/user-attachments/files/18011321/2024-12-04-7.log.gz)
Sorry this one has the correct version + error

EDIT: Yes can confirm when using the version 1.3.17 the server crashes and restarts. But when switching 1.3.14 the server runs just fine and he can join

**Comment by Globox1997** [comment]
Do you use the latest nameplate version?

**Comment by AzCreep** [comment]
yes i'm using the latest version

**Comment by win98x** [comment]
I can second this exact same string on my singleplayer world as well.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.
Time: 2025-01-03 23:08:18
Description: Exception in server tick loop
java.lang.NoSuchMethodError: 'void net.rpgdifficulty.api.MobStrengthener.changeAttributes(net.minecraft.class_1308, net.minecraft.class_1937)'
at knot//net.nameplate.network.NameplateServerPacket.lambda$init$0(NameplateServerPacket.java:26)
at knot//net.minecraft.class_3738.run(class_3738.java:18)
at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
at java.base/java.lang.Thread.run(Unknown Source)

And 
[2025-01-03-7[1].log](https://github.com/user-attachments/files/18305721/2025-01-03-7.1.log)
is the full log file. 

I can confirm that my world launches when RPGDifficulty is disabled, and I can also confirm that I am using the most recent version of Nameplate. It crashes at the moment that it begins to load the terrain. Hangs for about 5 seconds and then crashes. Hopefully this helps.

**Comment by Globox1997** [comment]
Update is on its way. Fixed with [https://github.com/Globox1997/Nameplate/commit/63b4d5af3e0e00cf7473848b7d4ef89faf92c765](https://github.com/Globox1997/Nameplate/commit/63b4d5af3e0e00cf7473848b7d4ef89faf92c765).
Please update nameplate.
